spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/ele_fence?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: DES@bC2Z7Jx+DA3Wx0rlnkeRVg==
    password: DES@CClgxAfU75Q96VBqWKi1Vg==

#server:
#  port: 8081









